app:
  name: document_classifier
  version: 1.0.0

fastapi:
  host: 0.0.0.0
  port: 8000
  reload: true

streamlit:
  host: localhost
  port: 8501

mlflow:
  tracking_uri: http://localhost:5000
  experiment_name: document_classification

monitoring:
  prometheus:
    enabled: true
    host: 0.0.0.0
    port: 9090
  grafana:
    enabled: true
    host: http://localhost:3000
    username: admin
    password: admin

model:
  type: resnet50
  input_size: [224, 224]
  classes: ["invoice", "ktp", "passport", "bank_statement"]
  checkpoint_path: ./models/resnet50_checkpoint.pth

logging:
  level: DEBUG
  file: ./logs/app.log
