version: 1
formatters:
  simple:
    format: "[%(asctime)s] [%(levelname)s] - %(message)s"
  detailed:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s:%(lineno)d] - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: ./logs/app.log

loggers:
  app_logger:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: WARNING
  handlers: [console]